// Authentication API
@AuthAPI_HostAddress = http://localhost:8081/api/Authenticate


// Register User API
POST {{AuthAPI_HostAddress}}/register
Content-Type: application/json

{
  "username": "iamsave2",
  "email": "save2@email.com",
  "password": "Save2@1234"
}

###

// Register Admin API
POST {{AuthAPI_HostAddress}}/register-admin
Content-Type: application/json

{
  "username": "punyapatadmin2",
  "email": "adminsave2@email.com",
  "password": "AdminSave2@1234"
}

###

// Login API
POST {{AuthAPI_HostAddress}}/login
Content-Type: application/json

{
  "username": "iamsamit",
  "password": "Samit@1234"
}